package com.skilldistillery.foodtruck;

public class FoodTruck {

	//do not have user input truck id
	//has food truck data only
	//id generated by in the FoodTruck constructor 
	//from a static field that is incremented as each truck is created.
	//add tostring method
	//highest rating can be tie or show first one
}
